[package]
name = "docspec-docx-reader-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
docspec-docx-reader = { path = ".." }

[[bin]]
name = "fuzz_docx_reader"
path = "fuzz_targets/fuzz_docx_reader.rs"
test = false
doc = false

[workspace]
