[package]
name = "docspec-html-reader"
version = "1.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "HTML to DocSpec event stream reader"
keywords = ["document", "conversion", "streaming", "html"]
categories = ["parsing"]

[dependencies]
docspec-core = { path = "../docspec-core", version = "1.0.0" }
html5gum = "0.8"

[lints]
workspace = true
